# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20068 import InlineResponse20068  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20068(unittest.TestCase):
    """InlineResponse20068 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20068(self):
        """Test InlineResponse20068"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20068.InlineResponse20068()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
